### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by Li1991** [kyu-sz/DeepMAR_deploy#1]
I am doing some things with person attribute recognition now. But, I am a newer.Can you tell me how to run it? I am looking forward to hearing from you. Thank you very much. @kyu-sz @dli2016

**Comment by kyu-sz** [comment]
You must have Caffe for the "master" branch or Caffe2 for the "caffe2" branch.
Then acquire the DeepMAR model from the author Dangwei Li, or train one by yourself.
Compile the project with CMake. There is a main function in the [test/test.cpp](test/test.cpp). Input the ID of GPU you are going to use, paths of the model and the path of the test image when calling the compiled executable.

**Comment by Li1991** [comment]
Thank you very much!
