### ISSUE TITLE
How to use it 

### ISSUE THREAD

**Issue by Li1991** [kyu-sz/DeepMAR_deploy#2]
Can you give the instructions of how to use it? Thank you very much! @kyu-sz @dli2016

**Comment by kyu-sz** [comment]
First of all, this repository is only designed as a submodule of [LaS-VPE-Platform](https://github.com/kyu-sz/LaS-VPE-Platform).
The "include" and "src" folder contains source codes of the DeepMAR class, which can be built into shared library.
The "test/test.cpp" contains sample codes of how to use the DeepMAR class.
The "jni" folder contains codes of JNI wrapping of DeepMAR. The corresponding Java class can be found [inside the LaS-VPE-Platform project](https://github.com/kyu-sz/LaS-VPE-Platform/blob/master/src/main/java/org/cripac/isee/alg/pedestrian/attr/DeepMARCaffe2Native.java).
To use it, you must first train a DeepMAR model by yourself, or obtain one from the authors of the DeepMAR (not me, contact Dangwei Li).

**Comment by Li1991** [comment]
您好，联系上了李党伟，获得了部分数据代码。实现过程发现一个问题，但李大神没回复，向您请教一下：

以下两种算法测出的结果不同

（1）       使用fc8层输出正负来确定二值标签，利用RAP数据集里的matlab代码计算的mA,accuracy,precision,recall和F1

（2）       利用train_test.prototxt里面的TEST，直接借助accuracy层获得结果

这两种方式下模型预测的值都是一样的啊，为什么计算这几个指标的答案却不相同呢？

麻烦您抽空回复一下喽

 

 

发件人: noreply@github.com [mailto:noreply@github.com] 代表 Ken Yu
发送时间: 2017年8月19日 0:31
收件人: kyu-sz/DeepMAR_deploy
抄送: Li1991; Author
主题: Re: [kyu-sz/DeepMAR_deploy] How to use it (#2)

 

First of all, this repository is only designed as a submodule of LaS-VPE-Platform <https://github.com/kyu-sz/LaS-VPE-Platform> .
The "include" and "src" folder contains source codes of the DeepMAR class, which can be built into shared library.
The "test/test.cpp" contains sample codes of how to use the DeepMAR class.
The "jni" folder contains codes of JNI wrapping of DeepMAR. The corresponding Java class can be found inside the LaS-VPE-Platform project <https://github.com/kyu-sz/LaS-VPE-Platform/blob/master/src/main/java/org/cripac/isee/alg/pedestrian/attr/DeepMARCaffe2Native.java> .
To use it, you must first train a DeepMAR model by yourself, or obtain one from the authors of the DeepMAR (not me, contact Dangwei Li).

**Comment by kyu-sz** [comment]
您好，我没有看过他的matlab评估代码，也许可以比较一下python里的评估跟他的评估有什么区别？

-----------------------------
Kai Yu, 余z, ヨカイ
Carnegie Mellon University 
Email: kyu_115s@hotmail.com
-----------------------------

**Comment by kyu-sz** [comment]
另外有一些groundtruth在python里做了处理，比如说性别的值的设定，这个可能导致结果不一样。

-----------------------------
Kai Yu, 余鎧, ヨカイ
Carnegie Mellon University
Email: kyu_115s@hotmail.com<mailto:kyu_115s@hotmail.com>
-----------------------------

On 30 Aug 2017, at 01:55, Li1991 <notifications@github.com<mailto:notifications@github.com>> wrote:

您好，联系上了李党伟，获得了部分数据代码。实现过程发现一个问题，但李大神没回复，向您请教一下：

以下两种算法测出的结果不同

（1） 使用fc8层输出正负来确定二值标签，利用RAP数据集里的matlab代码计算的mA,accuracy,precision,recall和F1

（2） 利用train_test.prototxt里面的TEST，直接借助accuracy层获得结果

这两种方式下模型预测的值都是一样的啊，为什么计算这几个指标的答案却不相同呢？

麻烦您抽空回复一下喽





发件人: noreply@github.com<mailto:noreply@github.com> [mailto:noreply@github.com] 代表 Ken Yu
发送时间: 2017年8月19日 0:31
收件人: kyu-sz/DeepMAR_deploy
抄送: Li1991; Author
主题: Re: [kyu-sz/DeepMAR_deploy] How to use it (#2)



First of all, this repository is only designed as a submodule of LaS-VPE-Platform <https://github.com/kyu-sz/LaS-VPE-Platform> .
The "include" and "src" folder contains source codes of the DeepMAR class, which can be built into shared library.
The "test/test.cpp" contains sample codes of how to use the DeepMAR class.
The "jni" folder contains codes of JNI wrapping of DeepMAR. The corresponding Java class can be found inside the LaS-VPE-Platform project <https://github.com/kyu-sz/LaS-VPE-Platform/blob/master/src/main/java/org/cripac/isee/alg/pedestrian/attr/DeepMARCaffe2Native.java> .
To use it, you must first train a DeepMAR model by yourself, or obtain one from the authors of the DeepMAR (not me, contact Dangwei Li).
